version: '3.9'

services:
    db:
        image: postgres:16-alpine
        restart: unless-stopped
        volumes:
            - pg_data:/var/lib/postgresql/data/
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=async_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=async_db
volumes:
    pg_data: